tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "awscli"
brew "mas"
brew "nvm"
brew "pyenv"
brew "rcm"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "adobe-creative-cloud"
cask "discord"
cask "firefox-developer-edition"
cask "font-new-york"
cask "font-sf-compact"
cask "font-sf-mono"
cask "font-sf-mono-for-powerline"
cask "font-sf-pro"
cask "iterm2"
cask "jetbrains-toolbox"
cask "messenger"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "nova"
cask "postbox"
cask "setapp"
cask "slack"
cask "spotify"
cask "visual-studio-code"
mas "1Password 7", id: 1333542190
mas "DaisyDisk", id: 411643860
mas "Momentum", id: 1564329434
